apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations: {}
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: tbd
    app.kubernetes.io/instance: tbd
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/name: nephio
    app.kubernetes.io/part-of: nephio
    app.kubernetes.io/version: tbd
  name: nephio-controller-network-role
rules:
- apiGroups:
  - inv.nephio.org
  resources:
  - links
  - nodes
  - endpoints
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - infra.nephio.org
  resources:
  - links/status
  - nodes/status
  - endpoints/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - ipam.alloc.nephio.org
  resources:
  - networkinstances
  - ipprefixes
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - ipam.alloc.nephio.org
  resources:
  - networkinstances/status
  - ipprefixes/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - vlan.alloc.nephio.org
  resources:
  - vlandatabases
  - vlans
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - vlan.alloc.nephio.org
  resources:
  - vlandatabases/status
  - vlans/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - config.nephio.org
  resources:
  - networks
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - config.nephio.org
  resources:
  - networks/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - infra2.nephio.org
  resources:
  - networks
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - infra2.nephio.org
  resources:
  - networks/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - infra2.nephio.org
  resources:
  - networkconfigs
  - networkconfigs/status
  - networks
  - networks/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - config.nephio.org
  resources:
  - networks
  - networks/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - infra.nephio.org
  resources:
  - repositories
  - repositories/status
  - tokens
  - tokens/status
  - workloadclusters
  - workloadclusters/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
