apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations: {}
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: tbd
    app.kubernetes.io/instance: tbd
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/name: nephio
    app.kubernetes.io/part-of: nephio
    app.kubernetes.io/version: tbd
  name: nephio-controller-target-role
rules:
- apiGroups:
  - '*'
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - inv.nephio.org
  resources:
  - targets
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - inv.nephio.org
  resources:
  - targets/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - config.nephio.org
  resources:
  - networks
  - networks/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - infra.nephio.org
  resources:
  - networks
  - networks/status
  - repositories
  - repositories/status
  - tokens
  - tokens/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
